FROM envoyproxy/envoy-alpine-dev:latest

RUN apk update
RUN apk add py3-pip
RUN apk add python3 bash curl       
RUN pip3 install -q Flask==0.11.1 requests==2.18.4       
RUN mkdir /code
ADD ./service.py /code

EXPOSE 8080

CMD ["python3", "/code/service.py"]
